language: node_js
node_js:
  - 14.15

jobs:
  include:
    - stage: build
      name: "Build the library"
      script: npm run build
    - stage: coverage
      name: "Collect coverage report"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - stage: deploy
      if: branch = master
      name: "Deploy to NPM"
      script: npm run release
