language: node_js
node_js:
  - 14.15

jobs:
  include:
    - stage: Collect coverage report
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
